ekf_filter_node:
  ros__parameters:
    # General filter settings
    use_sim_time:    true
    frequency:       50.0
    sensor_timeout:  0.1
    two_d_mode:      true
    publish_tf:      false

    # Inputs
    odom0:           /odom
    odom0_config:   [true, true, false,  false, false,  true,
                     false, false, false, false, false, false,
                     false, false, false]
    imu0:            /imu
    imu0_config:   [false, false, false,  true,  true,  true,
                    false, false, false,  true,  true,  true,
                    false, false, false]

    # Frames (must all be unique)
    map_frame:        map
    odom_frame:       odom
    base_link_frame:  base_link
    world_frame:      odom
